### ISSUE TITLE
deployment response data

### ISSUE THREAD

**Issue by eliecer2000** [stackery/wild-rydes-workshop#15]
Greetings, is there a flag when I run stackery that can return me when I deploy the resulting data in a .json file like amplify does for example when doing push? the file would contain the endpoint of the api rest, id app client of the cognito pool including the pool id itself.

Example:
```

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:123456789-xxxx-468f-9ee0-66b6bcce9ea5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xxxxxxxxxxx",
    "aws_user_pools_web_client_id": "546a5sdf4db1al4f42ual8g467jo",
};


export default awsmobile;
```

thk

**Comment by txase** [comment]
Hi @eliecer2000! Somehow we missed your issue. Sorry about that.

Yes, you can run `stackery describe --json` to output info about resources. That said, we just updated the workshop to show how to do a step like this more easily in the new [Website builder](https://docs.stackery.io/docs/api/nodes/Website/) resource.

I hope this addresses your question. I'm closing the issue, but feel free to reopen if it doesn't resolve the issue for you!
