### ISSUE TITLE
getting an error in module 4

### ISSUE THREAD

**Issue by theburningmonk** [stackery/wild-rydes-workshop#18]
getting this when I try to deploy:

![image](https://user-images.githubusercontent.com/546969/87538252-371bfb80-c69c-11ea-8d2b-5edecc06c614.png)

is this an alias that gets created by Stackery? I don't see in the instructions where I need to create this alias

**Comment by ryanycoleman** [comment]
Hey @theburningmonk I believe that's a bug in the website resource we'll address. In your template, find the WebsiteEventsPermission resource and this property should read function, not requestunicorn. 

> FunctionName: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:stackery-agent-commander

**Comment by txase** [comment]
This issue has been fixed in Stackery's visual editor. Thanks for reporting it!
